### ISSUE TITLE
Any plans to continue?

### ISSUE THREAD

**Issue by dumblob** [rikiji/redis-android#1]
Are there any plans to continue? Or do you know about some other initiative, which is developed and/or fully working on Android?

**Comment by wf9a5m75** [comment]
I have been developing on the forked repository. Actually I use this in my company products.
https://github.com/wf9a5m75/redis-android

**Comment by dumblob** [comment]
Hi @wf9a5m75, thanks for the pointer.

I've looked at it and I don't understand. There are no patches, no source code, nothing. Everything is just a precompiled .so libraries. Also one can't raise any issue, because you disabled the "Issues" functionality for the repository. I'm curious what are the reasons for publishing binaries and not allowing anyone to comment/raise_issues/ask_questions/propose_something...

Btw Salvatore has plans for running Redis on Android - he mentioned it at least once on his blog if I'm not mistaken (also look at https://redis.io/topics/ARM ). So it would make sense to join the effort and maybe even try to make a pull request to the official Redis repository.

**Comment by wf9a5m75** [comment]
updated.
https://github.com/wf9a5m75/redis-android

**Comment by dumblob** [comment]
Hi @wf9a5m75, glad to hear there are some changes.

May I first propose cleaning up the repository from all compilable binary files? I.e. `*.so` `*.a` `*.o` (don't forget to gitignore them). Then I'll look closer and try to propose ways how to avoid duplication and unnecessary content. Currently it seems to me, there is a whole redis repository included several times on various places. This disallows pushing any changes back to the [main redis repository](https://github.com/antirez/redis ) and thus I would propose using subrepositories.

Also I noticed there are included more versions of redis in https://github.com/wf9a5m75/redis-android/tree/master/repository/io/wf9a5m75/redis-android which doesn't make any sense to me. IMHO just one version should be supported at a time. Other versions shall definitely be not present.

**Comment by dumblob** [comment]
Discussion moved to https://github.com/wf9a5m75/redis-android/issues/1 .
